import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';

const canvas=document.querySelector('#game');
const scene=new THREE.Scene();scene.background=new THREE.Color(0x8bcdf1);scene.fog=new THREE.FogExp2(0x9bcfee,.0027);
const camera=new THREE.PerspectiveCamera(68,innerWidth/innerHeight,.08,500);camera.position.set(0,11,78);
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));composer.addPass(new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),.28,.5,.86));
const orbit=new OrbitControls(camera,canvas);orbit.enabled=false;orbit.enableDamping=true;orbit.dampingFactor=.06;orbit.target.set(0,6,-18);orbit.maxPolarAngle=Math.PI*.48;orbit.minDistance=18;orbit.maxDistance=130;

const hemi=new THREE.HemisphereLight(0xdff6ff,0x53684a,2.1);scene.add(hemi);const sun=new THREE.DirectionalLight(0xfff0d6,4);sun.position.set(-65,85,42);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-120;sun.shadow.camera.right=120;sun.shadow.camera.top=120;sun.shadow.camera.bottom=-120;sun.shadow.bias=-.00015;scene.add(sun);const fill=new THREE.DirectionalLight(0xb9dfff,.8);fill.position.set(70,28,30);scene.add(fill);

const M={concrete:new THREE.MeshStandardMaterial({color:0xe9ecec,roughness:.78,metalness:.02}),blue:new THREE.MeshStandardMaterial({color:0x063d9c,roughness:.48,metalness:.08}),blueDark:new THREE.MeshStandardMaterial({color:0x04266c,roughness:.42,metalness:.1}),accent:new THREE.MeshStandardMaterial({color:0x16c9ed,emissive:0x087d9d,emissiveIntensity:.8,roughness:.28}),glass:new THREE.MeshPhysicalMaterial({color:0x142738,roughness:.08,metalness:.05,transmission:.18,transparent:true,opacity:.78,ior:1.45,clearcoat:1}),road:new THREE.MeshStandardMaterial({color:0x2b3035,roughness:.92}),paver:new THREE.MeshStandardMaterial({color:0x9a6653,roughness:.86}),grass:new THREE.MeshStandardMaterial({color:0x397c2d,roughness:1}),metal:new THREE.MeshStandardMaterial({color:0x242a31,roughness:.36,metalness:.72}),white:new THREE.MeshStandardMaterial({color:0xf8fafb,roughness:.56}),wood:new THREE.MeshStandardMaterial({color:0x6f4a33,roughness:.82}),leaf:new THREE.MeshStandardMaterial({color:0x2f7a36,roughness:.95})};
const obstacles=[];function box(size,pos,mat=M.concrete,cast=true,ob=false){const m=new THREE.Mesh(new THREE.BoxGeometry(...size),mat);m.position.set(...pos);m.castShadow=cast;m.receiveShadow=true;scene.add(m);if(ob)obstacles.push(new THREE.Box3().setFromObject(m));return m}function cyl(r,h,pos,mat=M.metal,seg=16){const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,seg),mat);m.position.set(...pos);m.castShadow=true;m.receiveShadow=true;scene.add(m);return m}
function textPanel(text,w,h,color='#fff',bg='rgba(0,0,0,0)',font=120){const c=document.createElement('canvas');c.width=1024;c.height=256;const g=c.getContext('2d');g.fillStyle=bg;g.fillRect(0,0,1024,256);g.fillStyle=color;g.font=`900 ${font}px Arial`;g.textAlign='center';g.textBaseline='middle';g.shadowColor=color;g.shadowBlur=10;g.fillText(text,512,128);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const m=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:t,transparent:true,side:THREE.DoubleSide}));scene.add(m);return m}
function windowRow(start,count,step,y,z){for(let i=0;i<count;i++){box([6.2,3.3,.22],[start+i*step,y,z],M.glass,false);box([.32,3.6,.38],[start+i*step+3.35,y,z-.03],M.blueDark,false)}}
function shrub(x,z,s=1){cyl(.28,.8,[x,.4,z],M.wood,8);const crown=new THREE.Mesh(new THREE.SphereGeometry(1.25*s,12,8),M.leaf);crown.scale.y=.72;crown.position.set(x,1.45*s,z);crown.castShadow=true;scene.add(crown)}
function palm(x,z,h=20){cyl(.48,h,[x,h/2,z],M.wood,10);for(let i=0;i<11;i++){const a=i/11*Math.PI*2,leaf=box([.65,.22,7.5],[x+Math.cos(a)*2.7,h-.2,z+Math.sin(a)*2.7],M.leaf);leaf.rotation.y=-a;leaf.rotation.z=.08*Math.sin(a)}}
function car(x,z,color,rot=0){const mat=new THREE.MeshStandardMaterial({color,roughness:.32,metalness:.42});const body=box([4.8,1.25,2.2],[x,.82,z],mat);body.rotation.y=rot;const roof=box([2.7,.9,1.9],[x,1.75,z],M.glass);roof.rotation.y=rot;for(const dx of [-1.45,1.45])for(const dz of [-1.05,1.05]){const w=cyl(.39,.28,[x+dx*Math.cos(rot)-dz*Math.sin(rot),.38,z+dx*Math.sin(rot)+dz*Math.cos(rot)],M.metal,14);w.rotation.x=Math.PI/2}}

// terreno, rua, calçadas e estacionamento
box([190,.3,145],[0,-.25,0],M.grass,false);box([190,.16,20],[0,.02,56],M.road,false);for(let x=-86;x<87;x+=16)box([8,.03,.24],[x,.13,56],M.white,false);box([126,.16,59],[1,.03,21],M.road,false);box([126,.22,10],[1,.11,-9],M.paver,false);box([190,.18,4],[0,.08,45],M.concrete,false);
for(let x=-50;x<=50;x+=10){box([.13,.025,14],[x,.13,17],M.white,false);box([.13,.025,13],[x,.13,37],M.white,false)}

// fachada principal com volumes mais arquitetônicos
box([91,10.5,24],[4,5.25,-22],M.blue,true,true);box([54,6.4,19],[-8,13.4,-23],M.concrete,true,true);box([57,2,20],[-8,17.5,-23],M.blueDark,true,true);box([24,18,20],[39,9,-22],M.blueDark,true,true);windowRow(-36,7,10,4.3,-9.85);box([22,1.2,5.2],[39,9,-9],M.concrete,true);box([14,.38,5.8],[39,.22,-5.4],M.accent,true);box([17,.34,7],[39,.18,-7.6],M.concrete,true);box([4.2,7,.52],[32.7,4,-10],M.blue,true,true);box([4.2,7,.52],[45.3,4,-10],M.blue,true,true);box([7.2,6,.25],[39,3.5,-9.7],M.glass,true);const logo=textPanel('acritica',17,4,'#7cecff','rgba(0,0,0,0)',150);logo.position.set(39,14.2,-11.85);
// halo/logo circular
const ring=new THREE.Mesh(new THREE.TorusGeometry(2.1,.2,16,48),new THREE.MeshStandardMaterial({color:0x35dfff,emissive:0x169cc0,emissiveIntensity:2}));ring.position.set(39,17.1,-11.7);ring.rotation.x=Math.PI/2;scene.add(ring);

// jornal impresso / rádios
box([34,9.5,25],[-66,4.75,-22],M.concrete,true,true);box([35,1.6,26],[-66,10.3,-22],M.blueDark,true);for(let x=-78;x<=-57;x+=7)box([5,4.7,.22],[x,4.1,-9.35],M.glass);const jp=textPanel('JORNAL IMPRESSO',27,2.6,'#fff','rgba(0,0,0,0)',72);jp.position.set(-66,10.5,-8.9);
box([36,9.5,25],[72,4.75,-22],M.concrete,true,true);box([37,1.6,26],[72,10.3,-22],M.blueDark,true);const rp=textPanel('RÁDIOS',18,2.6,'#fff','rgba(0,0,0,0)',90);rp.position.set(72,10.5,-8.9);['CRÍTICA','MANAUS','POP','PRIME'].forEach((t,i)=>{const p=textPanel(t,7,1.5,i===2?'#ffd532':'#eaf6ff','rgba(0,0,0,0)',74);p.position.set(58+i*9,5.7,-8.95)});

// paisagismo / palmeiras
palm(1,-3,24);palm(10,-4,27);palm(-47,-3,18);[[-52,4],[-38,5],[-22,4],[24,5],[54,5],[65,5],[82,5],[-56,39],[-34,39],[29,39],[54,39],[79,39]].forEach(a=>shrub(...a,1.1));
// carros
[[-44,16,0xeeeeee],[-33,16,0x1fa9ca],[-22,16,0x223a2c],[-11,16,0xe6e6e6],[14,16,0x17191d],[27,16,0xf3f3f3],[49,16,0x273648],[63,16,0xe8e8e8],[-39,36,0x12151a],[-16,36,0xb53f34],[19,36,0xffffff],[44,36,0x202329],[72,36,0xf0f0f0]].forEach(a=>car(...a));

// grade frontal e portão
for(let x=-94;x<=94;x+=2.7)box([.1,4,.1],[x,2,47],M.metal,true);box([190,.25,.25],[0,.55,47],M.metal);box([190,.25,.25],[0,3.8,47],M.metal);for(let x=-90;x<=90;x+=18)box([.8,4.8,.8],[x,2.4,47],M.blue,true);box([28,5.3,.9],[-2,2.65,47],M.blue,true);const gate=textPanel('TV A CRÍTICA',20,2.3,'#fff','rgba(0,0,0,0)',90);gate.position.set(-2,5.25,46.45);gate.rotation.y=Math.PI;
// torre
for(const x of [-45,-41])box([.38,34,.38],[x,17,-33],M.metal,true);for(let y=2;y<34;y+=2.7){const cross=box([5,.14,.14],[-43,y,-33],M.metal);cross.rotation.z=(Math.floor(y)%2?.55:-.55)}
// luzes do estacionamento
for(const x of [-52,-25,4,33,62]){cyl(.16,8,[x,4,31],M.metal,10);const lamp=box([1.1,.25,.45],[x,8,31],new THREE.MeshStandardMaterial({color:0xffffff,emissive:0xe8f4ff,emissiveIntensity:3}),false);const light=new THREE.PointLight(0xdff4ff,9,16,2);light.position.set(x,7.6,31);scene.add(light)}

// controles
let mode='free',playing=false,yaw=Math.PI,pitch=0,runHeld=false;const keys={};addEventListener('keydown',e=>keys[e.code]=true);addEventListener('keyup',e=>keys[e.code]=false);function lookBy(dx,dy){yaw-=dx*.0028;pitch=Math.max(-1.38,Math.min(1.38,pitch-dy*.00245));camera.rotation.set(pitch,yaw,0,'YXZ')}addEventListener('mousemove',e=>{if(playing&&mode==='first'&&document.pointerLockElement===canvas)lookBy(e.movementX,e.movementY)});canvas.addEventListener('click',()=>{if(playing&&mode==='first'&&!matchMedia('(pointer:coarse)').matches)canvas.requestPointerLock?.()});
const joy=document.querySelector('#joy'),stick=document.querySelector('#stick'),look=document.querySelector('#look'),run=document.querySelector('#run');let jx=0,jy=0,jid=null,lid=null,lx=0,ly=0;function joyMove(e){const t=[...e.changedTouches].find(v=>v.identifier===jid);if(!t)return;const r=joy.getBoundingClientRect();let x=t.clientX-r.left-r.width/2,y=t.clientY-r.top-r.height/2,d=Math.hypot(x,y),m=42;if(d>m){x=x/d*m;y=y/d*m}jx=x/m;jy=y/m;stick.style.transform=`translate(${x}px,${y}px)`}joy?.addEventListener('touchstart',e=>{e.preventDefault();jid=e.changedTouches[0].identifier;joyMove(e)},{passive:false});joy?.addEventListener('touchmove',e=>{e.preventDefault();joyMove(e)},{passive:false});joy?.addEventListener('touchend',()=>{jid=null;jx=jy=0;stick.style.transform='translate(0,0)'},{passive:false});look?.addEventListener('touchstart',e=>{const t=e.changedTouches[0];lid=t.identifier;lx=t.clientX;ly=t.clientY},{passive:false});look?.addEventListener('touchmove',e=>{e.preventDefault();const t=[...e.changedTouches].find(v=>v.identifier===lid);if(t){lookBy(t.clientX-lx,t.clientY-ly);lx=t.clientX;ly=t.clientY}},{passive:false});look?.addEventListener('touchend',()=>lid=null,{passive:false});run?.addEventListener('touchstart',()=>runHeld=true);run?.addEventListener('touchend',()=>runHeld=false);
function setMode(next){mode=next;playing=true;document.body.classList.add('playing');document.body.classList.toggle('first',next==='first');document.querySelector('#menu').classList.add('hidden');if(next==='first'){orbit.enabled=false;camera.position.set(0,1.72,43);yaw=Math.PI;pitch=0;camera.rotation.set(0,yaw,0,'YXZ');if(!matchMedia('(pointer:coarse)').matches)canvas.requestPointerLock?.()}else{document.exitPointerLock?.();camera.position.set(0,16,82);camera.lookAt(0,6,-18);orbit.target.set(0,6,-18);orbit.enabled=true;orbit.update()}}
document.querySelector('#playFirst').onclick=()=>setMode('first');document.querySelector('#playFree').onclick=()=>setMode('free');document.querySelector('#home').onclick=()=>setMode(mode);document.querySelector('#menuBtn').onclick=()=>{playing=false;orbit.enabled=false;document.exitPointerLock?.();document.body.classList.remove('playing','first');document.querySelector('#menu').classList.remove('hidden')};let night=false;document.querySelector('#day').onclick=()=>{night=!night;scene.background.set(night?0x071326:0x8bcdf1);scene.fog.color.copy(scene.background);sun.intensity=night?.22:4;hemi.intensity=night?.35:2.1;renderer.toneMappingExposure=night?.72:1.12};
function collides(pos){const p=new THREE.Vector3(pos.x,1.4,pos.z),r=.42;return obstacles.some(b=>p.x>b.min.x-r&&p.x<b.max.x+r&&p.z>b.min.z-r&&p.z<b.max.z+r)}
const clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.035);if(playing&&mode==='first'){let f=(keys.KeyW?1:0)-(keys.KeyS?1:0)-jy,r=(keys.KeyD?1:0)-(keys.KeyA?1:0)+jx,n=Math.hypot(f,r);if(n>1){f/=n;r/=n}const speed=(keys.ShiftLeft||keys.ShiftRight||runHeld)?9.5:5.2;const forward=new THREE.Vector3(-Math.sin(yaw),0,-Math.cos(yaw));const right=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw));const delta=forward.multiplyScalar(f*speed*dt).add(right.multiplyScalar(r*speed*dt));const px=camera.position.clone();px.x+=delta.x;if(!collides(px))camera.position.x=px.x;const pz=camera.position.clone();pz.z+=delta.z;if(!collides(pz))camera.position.z=pz.z;camera.position.y=1.72}else if(orbit.enabled)orbit.update();composer.render()}animate();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight)});function hideBoot(){const b=document.querySelector('#boot');if(!b)return;b.style.opacity='0';b.style.pointerEvents='none';setTimeout(()=>b.remove(),500)}requestAnimationFrame(()=>requestAnimationFrame(()=>setTimeout(hideBoot,550)));setTimeout(hideBoot,2200);
