import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const canvas=document.getElementById('game'),loading=document.getElementById('loading'),startPanel=document.getElementById('startPanel'),startButton=document.getElementById('startButton'),locationLabel=document.getElementById('location'),mobileControls=document.getElementById('mobileControls'),joystick=document.getElementById('joystick'),joystickKnob=document.getElementById('joystickKnob'),lookPad=document.getElementById('lookPad'),runButton=document.getElementById('runButton');
window.addEventListener('error',e=>{loading.style.display='grid';loading.textContent='Erro ao carregar o jogo: '+(e.message||'erro desconhecido')});
const isTouch=matchMedia('(pointer: coarse)').matches||'ontouchstart'in window,lowPower=isTouch||Math.min(innerWidth,innerHeight)<700;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x07111f);scene.fog=new THREE.Fog(0x07111f,140,430);
const camera=new THREE.PerspectiveCamera(68,innerWidth/innerHeight,.1,800);camera.position.set(0,1.75,45);camera.rotation.order='YXZ';
const renderer=new THREE.WebGLRenderer({canvas,antialias:!lowPower,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,lowPower?.82:1.45));renderer.setSize(innerWidth,innerHeight,false);renderer.shadowMap.enabled=!lowPower;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;
let yaw=0,pitch=0,locked=false,mobileActive=false,running=false,joyX=0,joyY=0,currentMode={type:'full'};
function applyLook(dx,dy,f=.0022){yaw-=dx*f;pitch=Math.max(-1.42,Math.min(1.42,pitch-dy*f));camera.rotation.y=yaw;camera.rotation.x=pitch}
if(isTouch){mobileControls.style.display='block';startButton.onclick=()=>{mobileActive=true;startPanel.style.display='none'}}else{startButton.onclick=()=>canvas.requestPointerLock();document.addEventListener('pointerlockchange',()=>{locked=document.pointerLockElement===canvas;startPanel.style.display=locked?'none':'flex'});document.addEventListener('mousemove',e=>{if(locked)applyLook(e.movementX,e.movementY)})}
if(isTouch){let jid=null,lid=null,lx=0,ly=0;const rad=42,mj=e=>{const r=joystick.getBoundingClientRect();let dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,l=Math.hypot(dx,dy);if(l>rad){dx=dx/l*rad;dy=dy/l*rad}joyX=dx/rad;joyY=dy/rad;joystickKnob.style.transform=`translate(${dx}px,${dy}px)`};joystick.onpointerdown=e=>{jid=e.pointerId;joystick.setPointerCapture(jid);mj(e)};joystick.onpointermove=e=>{if(e.pointerId===jid)mj(e)};joystick.onpointerup=joystick.onpointercancel=()=>{jid=null;joyX=joyY=0;joystickKnob.style.transform='translate(0,0)'};lookPad.onpointerdown=e=>{lid=e.pointerId;lx=e.clientX;ly=e.clientY;lookPad.setPointerCapture(lid)};lookPad.onpointermove=e=>{if(e.pointerId===lid&&mobileActive){applyLook(e.clientX-lx,e.clientY-ly,.004);lx=e.clientX;ly=e.clientY}};lookPad.onpointerup=lookPad.onpointercancel=()=>lid=null;runButton.onpointerdown=()=>running=true;runButton.onpointerup=runButton.onpointercancel=()=>running=false}
scene.add(new THREE.HemisphereLight(0xbad9ff,0x17202c,lowPower?.9:1.2));const sun=new THREE.DirectionalLight(0xffffff,lowPower?1.15:1.65);sun.position.set(-45,65,35);scene.add(sun);
const MAT={white:new THREE.MeshStandardMaterial({color:0xf3f6f9,roughness:.48}),dark:new THREE.MeshStandardMaterial({color:0x101825,roughness:.42}),black:new THREE.MeshStandardMaterial({color:0x050810,roughness:.35}),blue:new THREE.MeshStandardMaterial({color:0x0b58c7,roughness:.3}),glass:new THREE.MeshPhysicalMaterial({color:0x183b57,transparent:true,opacity:.42,roughness:.1}),glossyBlue:new THREE.MeshPhysicalMaterial({color:0x061b3e,roughness:.14,metalness:.18,clearcoat:lowPower?.3:.8}),silver:new THREE.MeshStandardMaterial({color:0xb8c5d3,metalness:.35,roughness:.3})};
function box(n,s,p,m,parent=scene,ry=0){const q=new THREE.Mesh(new THREE.BoxGeometry(...s),m);q.name=n;q.position.set(...p);q.rotation.y=ry;q.castShadow=!lowPower;q.receiveShadow=!lowPower;parent.add(q);return q}function led(s,p,c=0x1bb7ff,parent=scene,ry=0){return box('LED',s,p,new THREE.MeshBasicMaterial({color:c,toneMapped:false}),parent,ry)}function point(p,c=0xffffff,i=14,parent=scene,r=20){if(lowPower)return;const l=new THREE.PointLight(c,i,r,2);l.position.set(...p);parent.add(l)}
function textTexture(text,bg='#063b93'){const c=document.createElement('canvas');c.width=512;c.height=256;const x=c.getContext('2d');x.fillStyle=bg;x.fillRect(0,0,512,256);x.fillStyle='#fff';x.textAlign='center';x.textBaseline='middle';x.font='bold 42px Arial';x.fillText(text,256,128);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}function sign(t,w,h,p,ry=0,bg='#063b93',parent=scene){const m=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:textTexture(t,bg),side:THREE.DoubleSide,toneMapped:false}));m.position.set(...p);m.rotation.y=ry;parent.add(m)}
const alertCanvas=document.createElement('canvas');alertCanvas.width=lowPower?640:1024;alertCanvas.height=lowPower?320:512;const ax=alertCanvas.getContext('2d'),alertTexture=new THREE.CanvasTexture(alertCanvas);alertTexture.colorSpace=THREE.SRGBColorSpace;function drawAlert(t=0){const w=alertCanvas.width,h=alertCanvas.height,g=ax.createLinearGradient(0,0,w,h);g.addColorStop(0,'#03256b');g.addColorStop(.5,'#12a6ee');g.addColorStop(1,'#0235a5');ax.fillStyle=g;ax.fillRect(0,0,w,h);ax.globalCompositeOperation='screen';for(let i=0;i<(lowPower?10:18);i++){let y=(i*h/18+t*.025+i*9)%h;ax.strokeStyle='rgba(130,230,255,.18)';ax.beginPath();ax.moveTo(0,y);ax.lineTo(w,y-55);ax.stroke()}ax.globalCompositeOperation='source-over';ax.save();ax.translate(w*.25,h*.25);ax.transform(1,0,-.12,1,0,0);ax.fillStyle='#e30b19';ax.fillRect(0,0,w*.19,h*.11);ax.strokeStyle='#fff';ax.lineWidth=3;ax.strokeRect(0,0,w*.19,h*.11);ax.fillStyle='#fff';ax.font=`italic bold ${h*.075}px Arial`;ax.textAlign='center';ax.textBaseline='middle';ax.fillText('NOVO',w*.095,h*.055);ax.restore();ax.textAlign='center';ax.font=`900 ${h*.27}px Arial Black,Arial`;ax.lineWidth=6;ax.strokeStyle='#01256e';ax.strokeText('ALERTA',w*.52,h*.59);const tg=ax.createLinearGradient(0,h*.4,0,h*.72);tg.addColorStop(0,'#29b8ff');tg.addColorStop(.55,'#0b63ee');tg.addColorStop(1,'#0131a1');ax.fillStyle=tg;ax.fillText('ALERTA',w*.52,h*.59);ax.font=`italic ${h*.05}px Arial`;ax.fillStyle='#10203a';ax.textAlign='right';ax.fillText('com Sikêra Jr.',w*.83,h*.75);alertTexture.needsUpdate=true}drawAlert();
function createFacade(){const g=new THREE.Group();g.name='Fachada';scene.add(g);box('solo',[125,1,90],[0,-.5,10],MAT.dark,g);box('predio',[94,16,28],[0,8,-4],MAT.white,g);box('faixa',[94,6.5,.7],[0,10.5,10.35],MAT.blue,g);box('entrada',[18,18,4],[35,9,11.7],MAT.blue,g)}
function createReception(){const g=new THREE.Group();g.name='Recepcao';g.position.set(0,0,-33);scene.add(g);box('piso',[58,.5,34],[0,.25,0],MAT.silver,g);box('parede',[58,14,.5],[0,7,-17],MAT.white,g);box('balcao',[18,4.5,5.5],[17,2.25,5],MAT.blue,g);sign('TV A CRÍTICA',14,5.2,[17,8.7,-16.72],0,'#0757bb',g);box('sofa',[20,2.2,5.5],[-8,1.1,7],MAT.white,g);led([42,.12,.12],[0,12.8,-16.4],0x1c9fff,g)}
function createCorridor(){const g=new THREE.Group();g.name='Corredor Principal';g.position.set(0,0,-68);scene.add(g);box('piso',[18,.4,78],[0,.2,-28],MAT.silver,g);box('L',[.5,13,78],[-9,6.5,-28],MAT.white,g);box('R',[.5,13,78],[9,6.5,-28],MAT.white,g);box('teto',[18,.45,78],[0,13,-28],MAT.black,g);led([.14,.14,74],[-8.6,11.7,-28],0x128cff,g);led([.14,.14,74],[8.6,11.7,-28],0x128cff,g);box('ramalPiso',[38,.4,12],[-19,.2,-64],MAT.silver,g);box('ramalParedeF',[38,13,.45],[-19,6.5,-70],MAT.white,g);box('ramalTeto',[38,.45,12],[-19,13,-64],MAT.black,g);sign('ESTÚDIO NOVO ALERTA',10,2.2,[-9.15,10.5,-64],Math.PI/2,'#0757bb',g)}
function createAlerta(){const g=new THREE.Group();g.name='Estudio Novo Alerta';g.position.set(-37,0,-132);scene.add(g);box('PisoEscuro',[50,.55,36],[0,.28,0],MAT.glossyBlue,g);box('PisoBranco',[15,.1,36],[-17.5,.61,0],MAT.white,g,-.035);box('Fundo',[50,16,.6],[0,8,-18],MAT.black,g);box('Esq',[.6,16,36],[-25,8,0],MAT.white,g);box('Dir',[.6,16,36],[25,8,0],MAT.dark,g);box('Teto',[50,.6,36],[0,16.1,0],MAT.black,g);
// porta real conectada ao corredor, com moldura e sinalização
box('ParedeEntradaL',[16,16,.6],[-17,8,18],MAT.dark,g);box('ParedeEntradaR',[22,16,.6],[14,8,18],MAT.dark,g);box('PortaTopo',[12,5,.6],[-3,13.5,18],MAT.dark,g);box('MolduraPortaL',[.6,11,.9],[-9,5.5,17.7],MAT.blue,g);box('MolduraPortaR',[.6,11,.9],[3,5.5,17.7],MAT.blue,g);box('MolduraPortaTopo',[12.6,.6,.9],[-3,11,17.7],MAT.blue,g);led([11.6,.14,.14],[-3,10.65,17.18],0x65dfff,g);sign('NOVO ALERTA',9,2.2,[-3,13.2,17.65],Math.PI,'#0757bb',g);
// L arquitetônico branco + LEDs
box('Lcol',[1.1,14,1],[-21.5,8,-16.5],MAT.white,g);box('Lteto',[41,1,1],[-1.5,14.6,-16.5],MAT.white,g);led([.2,12.7,.18],[-20.9,8,-15.9],0x66d9ff,g);led([39,.18,.18],[-1.5,14,-15.9],0x66d9ff,g);led([35,.16,.16],[-1,13.45,-14.5],0x168dff,g);
const sm=new THREE.MeshBasicMaterial({map:alertTexture,side:THREE.DoubleSide,toneMapped:false});const main=new THREE.Mesh(new THREE.PlaneGeometry(30,11.5),sm);main.position.set(-5.5,8,-17.65);g.add(main);const ret=new THREE.Mesh(new THREE.PlaneGeometry(8.5,11.5),sm.clone());ret.position.set(13.7,8,-13.35);ret.rotation.y=-Math.PI/2;g.add(ret);box('frameT',[31,.5,.6],[-5.5,14,-17.25],MAT.black,g);box('frameB',[31,.5,.6],[-5.5,2,-17.25],MAT.black,g);
// telão direito menor, dentro da parede e alinhado
box('PainelDireito',[12.5,14,.7],[18.2,8,-2.2],MAT.dark,g,-.08);const v=new THREE.Mesh(new THREE.PlaneGeometry(8.2,10.8),sm.clone());v.position.set(18.1,8,-1.75);v.rotation.y=-.08;g.add(v);box('frameV',[9,11.6,.5],[18.1,8,-2.05],MAT.black,g,-.08);
for(let i=0;i<4;i++){box('col',[1,12.5,1.2],[10.5+i*2.1,8,-15],MAT.blue,g);led([.1,11,.1],[10+i*2.1,8,-14.3],0x29a9ff,g)}for(let i=0;i<7;i++)box('ripa',[.35,11,.5],[-23,7.5,-12+i*1.8],MAT.white,g);
// câmeras de estúdio leves: geometria simples, sem luz dinâmica no celular
[[-12,2.2,5],[7,2.2,6],[15,2.2,10]].forEach((p,i)=>{const cg=new THREE.Group();cg.position.set(...p);g.add(cg);box('tripod',[.25,3,.25],[0,1.5,0],MAT.silver,cg);box('camera',[2,1.3,2.6],[0,3.4,0],MAT.black,cg);box('lens',[.65,.65,.8],[0,3.4,-1.55],MAT.silver,cg)});
[[-14,15.2,0],[-4,15.2,2],[7,15.2,1],[15,15.2,-2]].forEach((p,i)=>{box('spot',[2,.5,1.6],p,MAT.black,g);if(!lowPower&&i<3)point([p[0],13.6,p[2]],0xeef7ff,14,g,16)});}
createFacade();createReception();createCorridor();createAlerta();
window.addEventListener('tvacritica:start',e=>{currentMode=e.detail||{type:'full'};camera.position.set(0,1.75,currentMode.type==='program'?-28:45);if(isTouch){mobileActive=true;startPanel.style.display='none'}else{startPanel.style.display='flex';startButton.textContent='ENTRAR'}});
const keys=new Set();addEventListener('keydown',e=>keys.add(e.code));addEventListener('keyup',e=>keys.delete(e.code));const clock=new THREE.Clock();function move(dt){if(!(locked||mobileActive))return;let dx=0,dz=0;if(isTouch){dx=joyX;dz=joyY}else{if(keys.has('KeyW'))dz=-1;if(keys.has('KeyS'))dz=1;if(keys.has('KeyA'))dx=-1;if(keys.has('KeyD'))dx=1}let l=Math.hypot(dx,dz)||1;dx/=l;dz/=l;const sp=(running||keys.has('ShiftLeft'))?12:7.5,f=new THREE.Vector3(-Math.sin(yaw),0,-Math.cos(yaw)),r=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw));camera.position.addScaledVector(f,-dz*sp*dt);camera.position.addScaledVector(r,dx*sp*dt);camera.position.y=1.75;const z=camera.position.z;if(z>10)locationLabel.textContent='Fachada';else if(z>-55)locationLabel.textContent='Recepção';else if(z>-118)locationLabel.textContent='Corredor Principal';else locationLabel.textContent=currentMode.type==='program'?'Estúdio '+(currentMode.programName||'selecionado'):'Estúdios'}
let last=0;const interval=lowPower?125:70;function animate(t=0){requestAnimationFrame(animate);if(t-last>interval){drawAlert(t);last=t}move(Math.min(clock.getDelta(),.033));renderer.render(scene,camera)}addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio,lowPower?.82:1.45));renderer.setSize(innerWidth,innerHeight,false)});loading.style.display='none';animate();