// Menu inicial — apenas artes aprovadas aparecem.
const menu=document.getElementById('programMenu');
const menuGrid=document.getElementById('programGrid');
const menuTitle=document.getElementById('programMenuTitle');
const programs=[
 {id:'alerta',name:'Novo Alerta',destination:{x:-28,y:1.75,z:-90},approvedLogo:true},
 {id:'acritica-brasil',name:'A Crítica Brasil'},{id:'alerta-amazonas',name:'Alerta Amazonas'},
 {id:'alo-cidade',name:'Alô Cidade'},{id:'magazine',name:'Magazine'},{id:'manha-do-ar',name:'Jornal Manhã do Ar'},
 {id:'debate-eleitoral',name:'Debate Eleitoral'},{id:'a-bordo',name:'A Bordo'},{id:'the-box',name:'The Box'},
 {id:'acritica-news',name:'A Crítica News Madrugada e Tarde'},{id:'nosso-encontro',name:'Nosso Encontro'}
];
function createAnimatedAlertaLogo(host){const c=document.createElement('canvas');c.width=480;c.height=210;c.className='program-logo-canvas';host.appendChild(c);const x=c.getContext('2d');let raf=0,last=0;function draw(t=0){if(t-last<80){raf=requestAnimationFrame(draw);return}last=t;const w=c.width,h=c.height,g=x.createLinearGradient(0,0,w,h);g.addColorStop(0,'#03256b');g.addColorStop(.5,'#0b8ee6');g.addColorStop(1,'#0235a5');x.fillStyle=g;x.fillRect(0,0,w,h);x.save();x.globalCompositeOperation='screen';for(let i=0;i<10;i++){const y=(i*24+(t*.025+i*17)%h)%h;x.strokeStyle='rgba(130,230,255,.18)';x.lineWidth=1;x.beginPath();x.moveTo(0,y);x.lineTo(w,y-38);x.stroke()}x.restore();x.save();x.translate(w*.25,h*.23);x.transform(1,0,-.12,1,0,0);x.fillStyle='#e30b19';x.fillRect(0,0,90,29);x.strokeStyle='#fff';x.lineWidth=2;x.strokeRect(0,0,90,29);x.fillStyle='#fff';x.font='italic 700 19px Arial';x.textAlign='center';x.textBaseline='middle';x.fillText('NOVO',44,15);x.restore();x.textAlign='center';x.textBaseline='middle';x.font='900 61px Arial Black,Arial';x.lineWidth=4;x.strokeStyle='#01256e';x.strokeText('ALERTA',w*.52,h*.58);const tg=x.createLinearGradient(0,h*.35,0,h*.72);tg.addColorStop(0,'#29b8ff');tg.addColorStop(.5,'#0b63ee');tg.addColorStop(1,'#0131a1');x.fillStyle=tg;x.fillText('ALERTA',w*.52,h*.58);x.fillStyle='#10203a';x.font='italic 13px Arial';x.textAlign='right';x.fillText('com Sikêra Jr.',w*.82,h*.76);raf=requestAnimationFrame(draw)}raf=requestAnimationFrame(draw)}
function makeCard(p){const b=document.createElement('button');b.type='button';b.className='program-card'+(p.approvedLogo?' approved':' pending');b.dataset.program=p.id;const visual=document.createElement('span');visual.className='program-logo-placeholder';if(p.approvedLogo)createAnimatedAlertaLogo(visual);else{visual.classList.add('no-art');visual.textContent='ARTE EM BREVE'}const s=document.createElement('strong');s.textContent=p.name;const sm=document.createElement('small');sm.textContent=p.approvedLogo?'Entrar pela recepção':'Estúdio em preparação';b.append(visual,s,sm);if(p.approvedLogo)b.addEventListener('click',()=>chooseProgram(p));else b.disabled=true;return b}
function chooseProgram(p){window.TVACRITICA_GAME_MODE={type:'program',programId:p.id,programName:p.name,receptionStart:{x:0,y:1.75,z:-28},destination:p.destination||null,restrictOtherStudios:true};menu.style.display='none';window.dispatchEvent(new CustomEvent('tvacritica:start',{detail:window.TVACRITICA_GAME_MODE}))}
function chooseFullStation(){window.TVACRITICA_GAME_MODE={type:'full',programId:null,programName:'Emissora completa',restrictOtherStudios:false};menu.style.display='none';window.dispatchEvent(new CustomEvent('tvacritica:start',{detail:window.TVACRITICA_GAME_MODE}))}
programs.forEach(p=>menuGrid.appendChild(makeCard(p)));document.getElementById('fullStationButton').addEventListener('click',chooseFullStation);menuTitle.textContent='TV A CRÍTICA';menu.style.display='flex';